apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo
        image: jbergfeld/hello-k8s:b6.20210325.162124
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub-creds
